
project_id = "giluhqotfjpmofowvogn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
[functions.analyze-data]
verify_jwt = true

[functions.recommend-charts]
verify_jwt = true
